/* COMPILE-TIME DEFINITIONS */

#cmakedefine PACKAGE_NAME "@PACKAGE_NAME@"
#cmakedefine PACKAGE_DESCRIPTION "@PACKAGE_DESCRIPTION@"
#cmakedefine PACKAGE_STRING "@PACKAGE_STRING@"
#cmakedefine PACKAGE_VERSION "@PACKAGE_VERSION@"
#cmakedefine PACKAGE_TARNAME "@PACKAGE_TARNAME@"
#cmakedefine PACKAGE_URL "@PACKAGE_URL@"
#cmakedefine PACKAGE_BUGREPORT "@PACKAGE_BUGREPORT@"

/* loguru - no effect if building as library */
#cmakedefine LOGURU_WITH_STREAMS @LOGURU_WITH_STREAMS@
#cmakedefine LOGURU_REPLACE_GLOG @LOGURU_REPLACE_GLOG@
#cmakedefine LOGURU_FILENAME_WIDTH @LOGURU_FILENAME_WIDTH@
#cmakedefine LOGURU_THREADNAME_WIDTH @LOGURU_THREADNAME_WIDTH@
#cmakedefine LOGURU_VERBOSE_SCOPE_ENDINGS @LOGURU_VERBOSE_SCOPE_ENDINGS@
#cmakedefine LOGURU_SCOPE_TIME_PRECISION @LOGURU_SCOPE_TIME_PRECISION@

#cmakedefine USING_LOGURU @USING_LOGURU@
