# Preprocessing define pkg vars in config.h
set(PACKAGE_NAME ${PROJECT_NAME})
set(PACKAGE_DESCRIPTION ${PROJECT_DESCRIPTION})
set(PACKAGE_TARNAME ${PROJECT_NAME})
set(PACKAGE_VERSION "${PROJECT_VERSION}")
set(PACKAGE_URL ${PROJECT_HOMEPAGE_URL})
set(PACKAGE_BUGREPORT "comfortablynick@gmail.com")
set(PACKAGE_STRING "${PROJECT_NAME} ${PROJECT_VERSION}")
